Repository Nixtla/nixtla, pull requests merged in 2024-05, with the labels that each got.

#319 [DOCS] - Add a welcome/introduction page to the documentation
  nbs/docs/1_getting_started/1_introduction.ipynb
Labels: documentation

#312 Add capabilities notebooks
  nbs/docs/2_capabilities/anomaly_detection/01_quickstart.ipynb
  nbs/docs/2_capabilities/anomaly_detection/02_confidence_levels.ipynb
  nbs/docs/2_capabilities/anomaly_detection/03_anomaly_detection_date_features.ipynb
  nbs/docs/2_capabilities/anomaly_detection/04_anomaly_exogenous.ipynb
  nbs/docs/2_capabilities/forecast/01_quickstart.ipynb
  nbs/docs/2_capabilities/forecast/02_holidays_special_dates.ipynb
  nbs/docs/2_capabilities/forecast/03_exogenous_variables.ipynb
  nbs/docs/2_capabilities/forecast/04_categorical_variables.ipynb
  nbs/docs/2_capabilities/forecast/05_multiple_series.ipynb
  nbs/docs/2_capabilities/forecast/06_irregular_timestamps.ipynb
  nbs/docs/2_capabilities/forecast/07_prediction_intervals.ipynb
  nbs/docs/2_capabilities/forecast/08_finetuning.ipynb
  nbs/docs/2_capabilities/forecast/09_custom_loss_function.ipynb
  nbs/docs/2_capabilities/forecast/10_cross_validation.ipynb
  nbs/docs/2_capabilities/forecast/11_longhorizon.ipynb
  setup.py
Labels: documentation

#333 [FIX] Mintlify prefixes, readme file dirs
  nbs/docs/capabilities/000_capabilities.ipynb
  nbs/mint.json
Labels: documentation, fix

#321 Electricity demand use case
  .github/workflows/ci.yaml
  nbs/docs/use-cases/3_electricity_demand.ipynb
  nbs/docs/use-cases/4_intermittent_demand.ipynb
  nbs/mint.json
Labels: documentation

#342 [FIX] SDK Reference
  action_files/readme_com/create_readme_docs.sh
  nbs/docs/reference/01_nixtla_client.ipynb
  nbs/docs/reference/02_date_features.ipynb
  nbs/docs/reference/03_excel_addin.ipynb
  nbs/mint.json
Labels: documentation, fix

#295 [FIX] Raise warning on missing X_df when df has exogenous
  nbs/nixtla_client.ipynb
  nixtla/nixtla_client.py
Labels: fix

#343 Better intro/welcome page for doc
  nbs/docs/getting-started/1_introduction.ipynb
  nbs/img/timegpt_archi.png
Labels: documentation

#344 a few updates to getting started
  nbs/docs/getting-started/2_quickstart.ipynb
  nbs/docs/getting-started/3_setting_up_your_api_key.ipynb
  nbs/docs/tutorials/14_hierarchical_forecasting.ipynb
  nbs/img/dashboard.png
Labels: documentation

#339 [DOC] - Reduce code blocks in capabilties
  nbs/docs/capabilities/anomaly-detection/01_quickstart.ipynb
  nbs/docs/capabilities/anomaly-detection/02_anomaly_exogenous.ipynb
  nbs/docs/capabilities/anomaly-detection/03_anomaly_detection_date_features.ipynb
  nbs/docs/capabilities/anomaly-detection/04_confidence_levels.ipynb
  nbs/docs/capabilities/forecast/01_quickstart.ipynb
  nbs/docs/capabilities/forecast/02_exogenous_variables.ipynb
  nbs/docs/capabilities/forecast/03_holidays_special_dates.ipynb
  nbs/docs/capabilities/forecast/04_categorical_variables.ipynb
  nbs/docs/capabilities/forecast/05_longhorizon.ipynb
  nbs/docs/capabilities/forecast/06_multiple_series.ipynb
  nbs/docs/capabilities/forecast/07_finetuning.ipynb
  nbs/docs/capabilities/forecast/08_custom_loss_function.ipynb
  nbs/docs/capabilities/forecast/09_cross_validation.ipynb
  nbs/docs/capabilities/forecast/10_prediction_intervals.ipynb
  nbs/docs/capabilities/forecast/11_irregular_timestamps.ipynb
  nbs/docs/getting-started/1_introduction.ipynb
  nbs/docs/tutorials/20_anomaly_detection.ipynb
  nbs/mint.json
Labels: documentation

#352 [FIX] Hotfix for old SDK link removal
  action_files/readme_com/create_readme_docs.sh
Labels: fix

#340 [FEAT] What if - pricing in retail scenario
  nbs/docs/tutorials/19_missing_values.ipynb
  nbs/docs/use-cases/5_what_if_pricing_scenarios_in_retail.ipynb
  nbs/mint.json
Labels: documentation, feature

#341 Hotfix for links in documentation
  nbs/docs/getting-started/2_quickstart.ipynb
  nbs/docs/getting-started/3_setting_up_your_api_key.ipynb
  nbs/docs/getting-started/4_data_requirements.ipynb
  nbs/docs/getting-started/5_faq.ipynb
  nbs/docs/getting-started/6_glossary.ipynb
  nbs/docs/tutorials/05_multiple_series.ipynb
  nbs/docs/tutorials/06_finetuning.ipynb
  nbs/docs/tutorials/12_irregular_timestamps.ipynb
  nbs/docs/tutorials/15_missing_values.ipynb
  nbs/docs/tutorials/16_computing_at_scale.ipynb
  nbs/docs/tutorials/17_computing_at_scale_spark_distributed.ipynb
  nbs/docs/tutorials/18_computing_at_scale_dask_distributed.ipynb
  nbs/docs/tutorials/19_computing_at_scale_ray_distributed.ipynb
  nbs/mint.json
Labels: documentation

#349 [FIX] Colab-flag
  nbs/docs/capabilities/anomaly-detection/01_quickstart.ipynb
  nbs/docs/capabilities/anomaly-detection/02_anomaly_exogenous.ipynb
  nbs/docs/capabilities/anomaly-detection/03_anomaly_detection_date_features.ipynb
  nbs/docs/capabilities/anomaly-detection/04_confidence_levels.ipynb
  nbs/docs/capabilities/forecast/01_quickstart.ipynb
  nbs/docs/capabilities/forecast/02_exogenous_variables.ipynb
  nbs/docs/capabilities/forecast/03_holidays_special_dates.ipynb
  nbs/docs/capabilities/forecast/04_categorical_variables.ipynb
  nbs/docs/capabilities/forecast/05_longhorizon.ipynb
  nbs/docs/capabilities/forecast/06_multiple_series.ipynb
  nbs/docs/capabilities/forecast/07_finetuning.ipynb
  nbs/docs/capabilities/forecast/08_custom_loss_function.ipynb
  nbs/docs/capabilities/forecast/09_cross_validation.ipynb
  nbs/docs/capabilities/forecast/10_prediction_intervals.ipynb
  nbs/docs/capabilities/forecast/11_irregular_timestamps.ipynb
  nbs/docs/getting-started/2_quickstart.ipynb
  nbs/docs/tutorials/01_exogenous_variables.ipynb
  nbs/docs/tutorials/02_holidays.ipynb
  nbs/docs/tutorials/03_categorical_variables.ipynb
  nbs/docs/tutorials/04_longhorizon.ipynb
  nbs/docs/tutorials/05_multiple_series.ipynb
  nbs/docs/tutorials/06_finetuning.ipynb
  nbs/docs/tutorials/07_loss_function_finetuning.ipynb
  nbs/docs/tutorials/08_cross_validation.ipynb
  nbs/docs/tutorials/09_historical_forecast.ipynb
  nbs/docs/tutorials/10_uncertainty_quantification_with_quantile_forecasts.ipynb
  nbs/docs/tutorials/11_uncertainty_quantification_with_prediction_intervals.ipynb
  nbs/docs/tutorials/12_irregular_timestamps.ipynb
  nbs/docs/tutorials/13_bounded_forecasts.ipynb
  nbs/docs/tutorials/14_hierarchical_forecasting.ipynb
  nbs/docs/tutorials/15_missing_values.ipynb
  nbs/docs/tutorials/17_computing_at_scale_spark_distributed.ipynb
  nbs/docs/tutorials/18_computing_at_scale_dask_distributed.ipynb
  nbs/docs/tutorials/19_computing_at_scale_ray_distributed.ipynb
  nbs/docs/tutorials/20_anomaly_detection.ipynb
  nbs/docs/use-cases/1_forecasting_web_traffic.ipynb
  nbs/docs/use-cases/2_bitcoin_price_prediction.ipynb
  nbs/docs/use-cases/3_electricity_demand.ipynb
  nbs/docs/use-cases/4_intermittent_demand.ipynb
  nbs/docs/use-cases/5_what_if_pricing_scenarios_in_retail.ipynb
  nbs/utils.ipynb
  nixtla/_modidx.py
  nixtla/utils.py
Labels: documentation, feature, fix

#357 [DOC] Add azure callouts to use cases
  nbs/docs/use-cases/1_forecasting_web_traffic.ipynb
  nbs/docs/use-cases/2_bitcoin_price_prediction.ipynb
  nbs/docs/use-cases/3_electricity_demand.ipynb
  nbs/docs/use-cases/4_intermittent_demand.ipynb
  nbs/docs/use-cases/5_what_if_pricing_scenarios_in_retail.ipynb
Labels: documentation, feature
