Repository Nixtla/nixtla, pull requests merged in 2024-08, with the labels that each got.

#429 feat: call v2 endpoints
  .github/workflows/build-docs.yaml
  .github/workflows/ci.yaml
  .github/workflows/deploy-readme.yaml
  .github/workflows/models-performance.yaml
  .gitignore
  CONTRIBUTING.md
  action_files/models_performance/main.py
  environment.yml
  experiments/azure-automl-forecasting/src/nixtla_timegpt.py
  experiments/prophet/src/timegpt_exp.py
  nbs/distributed.nixtla_client.ipynb
  nbs/docs/reference/01_nixtla_client.ipynb
  nbs/docs/tutorials/03_categorical_variables.ipynb
  nbs/docs/tutorials/14_hierarchical_forecasting.ipynb
  nbs/docs/tutorials/17_computing_at_scale_spark_distributed.ipynb
  nbs/docs/tutorials/18_computing_at_scale_dask_distributed.ipynb
  nbs/docs/tutorials/19_computing_at_scale_ray_distributed.ipynb
  nbs/nixtla_client.ipynb
  nixtla/__init__.py
  nixtla/_modidx.py
  nixtla/distributed/__init__.py
  nixtla/distributed/nixtla_client.py
  nixtla/nixtla_client.py
  settings.ini
  setup.py
Labels: feature

#441 [BUG]: close img tag in introduction notebook
  nbs/docs/getting-started/1_introduction.ipynb
Labels: bug, documentation

#447 docs: add polars quickstart
  nbs/docs/getting-started/21_polars_quickstart.ipynb
  nbs/docs/getting-started/4_data_requirements.ipynb
  nbs/mint.json
Labels: documentation
