Repository Nixtla/nixtla, pull requests merged in 2024-10, with the labels that each got.

#471 FEAT: Add finetune_depth parameter
  nbs/docs/capabilities/forecast/07_finetuning.ipynb
  nbs/docs/tutorials/06_finetuning.ipynb
  nbs/src/nixtla_client.ipynb
  nixtla/nixtla_client.py
Labels: feature

#494 enh: improve short series error message
  nbs/src/nixtla_client.ipynb
  nixtla/nixtla_client.py
Labels: enhancement

#497 DOCS: Add finetune_depth to tutorial on improving accuracy
  nbs/docs/tutorials/22_how_to_improve_forecast_accuracy.ipynb
Labels: documentation

#508 Updating Azure getting started guide.
  nbs/docs/getting-started/22_azure_quickstart.ipynb
Labels: documentation

#505 breaking: add `hist_exog_list` argument to forecast
  nbs/src/nixtla_client.ipynb
  nixtla/nixtla_client.py
Labels: breaking change

#511 enh: warn when overriding model in Azure endpoint
  nbs/src/nixtla_client.ipynb
  nixtla/nixtla_client.py
Labels: enhancement

#504 breaking: raise error for gaps in series
  .github/workflows/lint.yaml
  .pre-commit-config.yaml
  README.md
  nbs/docs/capabilities/anomaly-detection/01_quickstart.ipynb
  nbs/docs/capabilities/anomaly-detection/03_anomaly_detection_date_features.ipynb
  nbs/docs/capabilities/anomaly-detection/04_confidence_levels.ipynb
  nbs/docs/capabilities/forecast/11_irregular_timestamps.ipynb
  nbs/docs/getting-started/1_introduction.ipynb
  nbs/docs/getting-started/5_faq.ipynb
  nbs/docs/tutorials/08_cross_validation.ipynb
  nbs/docs/tutorials/120_special_topics.ipynb
  nbs/docs/tutorials/12_irregular_timestamps.ipynb
  nbs/docs/tutorials/20_anomaly_detection.ipynb
  nbs/mint.json
  nbs/src/nixtla_client.ipynb
  nixtla/nixtla_client.py
  setup.py
Labels: breaking change
