Repository Nixtla/nixtla, pull requests merged in 2024-11, with the labels that each got.

#524 fix(deps): bump utils
  nixtla/__init__.py
  settings.ini
  setup.py
Labels: fix

#538 fix: cleaned the FAQ related to API validation
  nbs/docs/getting-started/5_faq.ipynb
Labels: documentation

#534 feat: add hist_exog_list argument to cross_validation
  nbs/src/nixtla_client.ipynb
  nixtla/nixtla_client.py
Labels: feature
