Repository Nixtla/nixtla, pull requests merged in 2024-09, with the labels that each got.

#448 FEAT: Add feature contributions as attribute and tutorial on how to use
  .github/workflows/models-performance.yaml
  nbs/docs/tutorials/21_shap_values.ipynb
  nbs/mint.json
  nbs/src/nixtla_client.ipynb
  nixtla/_modidx.py
  nixtla/nixtla_client.py
Labels: feature

#456 [FEAT] - Raise error when payload is too large and suggest number of partitions
  nbs/src/nixtla_client.ipynb
  nixtla/nixtla_client.py
Labels: enhancement, feature

#449 [DOCS] Add API call count FAQ
  nbs/docs/getting-started/5_faq.ipynb
Labels: documentation

#478 feat: support newer azure deployments
  nbs/src/nixtla_client.ipynb
  nixtla/_modidx.py
  nixtla/nixtla_client.py
  setup.py
Labels: feature
