Repository Nixtla/nixtla, pull requests merged in 2024-12, with the labels that each got.

#532 feat: support custom and integer frequencies
  nbs/src/nixtla_client.ipynb
  nixtla/nixtla_client.py
  setup.py
Labels: feature

#559 feat: zstd-compress requests over 1MB
  nbs/src/nixtla_client.ipynb
  nixtla/nixtla_client.py
  setup.py
Labels: feature

#570 [DOCS] Fixes two docs issues
  nbs/docs/getting-started/41_pricing.ipynb
  nbs/docs/getting-started/5_faq.ipynb
  nbs/docs/tutorials/14_hierarchical_forecasting.ipynb
Labels: documentation

#562 feat: saving and re-using fine-tuned models
  nbs/docs/reference/01_nixtla_client.ipynb
  nbs/src/nixtla_client.ipynb
  nixtla/_modidx.py
  nixtla/nixtla_client.py
  settings.ini
Labels: feature

#569 docs: FAQ | formatting fix
  CONTRIBUTING.md
  nbs/docs/getting-started/5_faq.ipynb
  nbs/nbdev.yml
Labels: documentation

#573 enh: update validate_api_key to use GET request
  nbs/src/nixtla_client.ipynb
  nixtla/nixtla_client.py
Labels: enhancement

#576 enh: use GET request for model_params
  nbs/src/nixtla_client.ipynb
  nixtla/_modidx.py
  nixtla/nixtla_client.py
Labels: enhancement

#578 docs: cleanup
  nbs/_quarto.yml
  nbs/docs/getting-started/41_pricing.ipynb
  nbs/docs/getting-started/5_faq.ipynb
  nbs/docs/reference/04_nixtlar.ipynb
  nbs/docs/tutorials/19_computing_at_scale_ray_distributed.ipynb
Labels: documentation

#580 docs: updated to include `fill_gaps` capability for multiple time series
  nbs/docs/tutorials/15_missing_values.ipynb
  settings.ini
Labels: documentation
