Repository Nixtla/nixtla, pull requests merged in 2025-01, with the labels that each got.

#546 FEAT: online anomaly detection
  nbs/docs/capabilities/anomaly-detection/00_anomaly_detection.ipynb
  nbs/docs/capabilities/anomaly-detection/02_anomaly_exogenous.ipynb
  nbs/docs/capabilities/anomaly-detection/03_anomaly_detection_date_features.ipynb
  nbs/docs/capabilities/historical-anomaly-detection/00_historical_anomaly_detection.ipynb
  nbs/docs/capabilities/historical-anomaly-detection/01_quickstart.ipynb
  nbs/docs/capabilities/historical-anomaly-detection/02_anomaly_exogenous.ipynb
  nbs/docs/capabilities/historical-anomaly-detection/03_anomaly_detection_date_features.ipynb
  nbs/docs/capabilities/historical-anomaly-detection/04_confidence_levels.ipynb
  nbs/docs/capabilities/online-anomaly-detection/00_online_anomaly_detection.ipynb
  nbs/docs/capabilities/online-anomaly-detection/01_quickstart.ipynb
  nbs/docs/capabilities/online-anomaly-detection/02_adjusting_detection_process.ipynb
  nbs/docs/capabilities/online-anomaly-detection/03_univariate_vs_multivariate_anomaly_detection.ipynb
  nbs/docs/tutorials/20_anomaly_detection.ipynb
  nbs/mint.json
  nbs/src/nixtla_client.ipynb
  nixtla/_modidx.py
  nixtla/nixtla_client.py
Labels: feature

#591 [FIX] Contiguity on exogenous
  nbs/src/nixtla_client.ipynb
  nixtla/__init__.py
  nixtla/nixtla_client.py
  settings.ini
Labels: fix

#595 docs: update changelog
  CHANGELOG.md
Labels: documentation
